import { dbConnect } from "./DB/connection.js";
import userRouter from "./src/modules/user/user.router.js";
import shopRouter from "./src/modules/Shop/shop.router.js";
import gymRouter from "./src/modules/gym/gym.router.js";
import coachRouter from "./src/modules/coach/coach.router.js";
import otherRouter from "./src/modules/other/Other.router.js";
import dotenv from "dotenv";
dotenv.config();
import express from "express";
import cors from "cors";
import mealRouter from "./src/modules/meal/meal.router.js";
const port = process.env.PORT;
const app = express();
app.use(cors());
app.use(express.json());
app.use("/user", userRouter);
app.use("/shop", shopRouter);
app.use("/gym", gymRouter);
app.use("/coach", coachRouter);
app.use("/other", otherRouter);
app.use("/meal", mealRouter);
app.use("*", (req, res) => res.status(404).json("Route not found"));
await dbConnect();
app.listen(port, () => console.log(`Server is running on port ${port}`));
