import { dbConnect } from "./DB/connection.js";
import userRouter from "./src/modules/user/user.router.js";
import shopRouter from "./src/modules/Shop/shop.router.js";
import gymRouter from "./src/modules/gym/gym.router.js";
import coashRouter from "./src/modules/coash/coash.router.js";
import dotenv from "dotenv";
dotenv.config();
import express from "express";
import cors from "cors";
const port = process.env.PORT;
const app = express();
app.use(cors());
app.use(express.json());
app.use("/user", userRouter);
app.use("/shop", shopRouter);
app.use("/gym", gymRouter);
app.use("/coash", coashRouter);

await dbConnect();
app.listen(port, () => console.log(`Server is running on port ${port}`));
