import { Router } from "express";
import { asyncHandler } from "../../utils/asynchandler.js";
import { getAllGyms, addGym, getGym } from "../gym/gym.controller.js";
import { GymSchema, getGymSchema } from "../gym/gym.schema.js";
import { validation } from "../../middleware/validation.middleware.js";
let gymRouter = Router();
gymRouter.get("/getAllGyms", asyncHandler(getAllGyms));
gymRouter.post("/getGym", validation(getGymSchema), asyncHandler(getGym));
gymRouter.post("/addGym", validation(GymSchema), asyncHandler(addGym));
export default gymRouter;
