import { Router } from "express";
import { asyncHandler } from "../../utils/asynchandler.js";
import { getAllGyms, addGym, getGym } from "./gym.controller.js";
import { UserSchema, getUserSchema, EmailSchema } from "../user/user.schema.js";
import { validation } from "../../middleware/validation.middleware.js";
let gymRouter = Router();
gymRouter.get("/getAllGyms", asyncHandler(getAllGyms));
gymRouter.post("/getUser", validation(getUserSchema), asyncHandler(getGym));
gymRouter.post("/addGym", validation(UserSchema), asyncHandler(addGym));
export default gymRouter;
